spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
custom-datasource:
  url: ${HEROKU_POSTGRESQL_YELLOW_URL:postgres://nikitapospolita:@localhost:5432/nikitapospolita}
  ssl-enabled: true

bot:
  hosted.url: ${HOSTED_URL:localhost}
  token: ${BOT_TOKEN:test}
  domain:
    adminId: ${ADMIN_ID:23452397}

server.port: ${PORT:8080}

admin:
  login: ${ADMIN_LOGIN:test}
  pass: ${ADMIN_PASS:test}
