spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: "jdbc:${HEROKU_POSTGRESQL_YELLOW_URL}"

bot:
  hosted.url: ${HOSTED_URL:localhost}
  token: ${BOT_TOKEN:test}
  domain:
    adminId: ${ADMIN_ID:23452397}

server.port: ${PORT:8080}