spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
custom-datasource:
  url: ${HEROKU_POSTGRESQL_YELLOW_URL:postgres://n.pospolita:@localhost:5432/n.pospolita}
  ssl-enabled: true


bot:
  hosted.url: ${HOSTED_URL:localhost}
  token: ${BOT_TOKEN:test}
  domain:
    adminId: ${ADMIN_ID:23452397}

server.port: ${PORT:8080}