# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: gradle

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runOnGitHub
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true